### ISSUE TITLE
Pink button on ibGib tutorial

### ISSUE THREAD

**Issue by bill-mybiz** [ibgib/mobileGib#87]
On the tutorial, the button just shows as a pink outline. It still works, just not a blue button. The other screens are normal.

**Comment by bill-mybiz** [comment]
I came across something yesterday in the common [Gib actualizer at line 154](https://github.com/ibgib/mobileGib/blob/6cfb2a2d77b49f2e68cbe5404d564eaf0c905ee2/Source/Android/mobileGib/mobileGib.Common.Androidish/Activities/GibActivityUsesViewPager.cs) that had a pink border around the blue Gib button.

I have a comment that says it is for debugging something, so I think this is why the button has the pink border. It still doesn't explain why the button would show as disabled when it is not disabled though.

**Comment by obrob** [comment]
Maybe this line since it checks for blue instead of pink?:

GibButton_Blue.Enabled = _FeedbackFragment.HasColorFeedback(GibColor.Blue);

**Comment by bill-mybiz** [comment]
Could be. I haven't checked it again since commenting out the pink line. I just happened to run across the line and remember this issue, saying "Hmmm, maybe this has to do with that pink border thing." I'm going to check it here in a little bit as soon as I get a refresh icon that looks like my other icons (not a trivial thing apparently).

**Comment by bill-mybiz** [comment]
Ah, now I remember why I didn't check it out immediately. I still don't have a solution for either languageGib or ibGib at the moment, since my current solution got somehow fubarred and crashes vs 2015 when I try to open it (and I can't use Xamarin Studio because it can't update the PCLs). I will be making those solution files pretty soon here after I get a few more tweaks with coffeeGib going.

**Comment by bill-mybiz** [comment]
This is fixed now that we are using the floating action buttons.
